version: '3.9'
services:
  segelflug_web:
    image: segelflug_web_img
    build:
      context: ./..
      dockerfile: ./docker/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      - SEGELFLUG_DB_SYSTEM=mysql
      - SEGELFLUG_DB_HOST=segelflug_db
      - SEGELFLUG_DB_NAME=segelflug_db
      - SEGELFLUG_DB_USER=segelflug_db_user
      - SEGELFLUG_DB_PASS_FILE=/run/secrets/db_password
    secrets:
      - db_password
    depends_on:
      - "segelflug_db"
  segelflug_db:
    image: segelflug_db_img
    build:
      context: database
    ports:
      - "3306:3306"
    environment:
      - MARIADB_DATABASE=segelflug_db
      - MARIADB_USER=segelflug_db_user
      - MARIADB_PASSWORD_FILE=/run/secrets/db_password
#      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/db_admin_password  # for db root access
    secrets:
      - db_password
#      - db_admin_password          # for db root access
    volumes:
      - type: volume
        source: segelflug_data_vol
        target: /var/lib/mysql
secrets:
  db_password:
    file: password_db_user.txt
#  db_admin_password:               # for db root access
#    file: password_db_admin.txt    # for db root access
volumes:
  segelflug_data_vol:
    driver: local